name: JS tests
on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  fleet-vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - run: node --version
      - run: npm ci
      - run: npm test
      - run: npm run test:driver
